server:
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  data:
    mongodb:
      uri: ENC(L6iHx2pLNBhXcyl+0zQERCKGHkt+N21FxPil8/c7JigZRGW012tC8GilDiXlVGYzPWaE+Z+Algt1kY0IVodf6jDwK4k6/tb4)

  elasticsearch:
    uris: ENC(GVWnAtVWWHX3mGclYbpVDmwKro9OZ+hKZw1+jTvE+Wo=)
    username: ENC(6UJ5jCmUqP1qZ58DFEiR1A==)
    password: ENC(cqqQm6974Rp+pmTGLGQXGfTzz/AvYewm0oAIs1lxPys=)

  datasource:
    url: ENC(lOFswiNgkkKFVYcwvYjD6SjBxBjdd98SV7GocEaulhDjhhQbtUO9uoSQB5O9uCg8ClK5mzgXiWg=)
    username: ENC(9m9o70ex2187SXtUNb1JQA==)
    password: ENC(Wstc5/so3a0smxXFvZP5pvCfQhdj10v007R2AGIcNY8=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 30

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: none # 엔티티 변경 시 데이터베이스 업데이트
  apple:
    path: ENC(Tg8LdfoWL+xcdboaDmi2xr8ew05VgLl54W0vvNzH9l4=)
    client: ENC(Z7UoHZBIg7j59FN7D/MTUjltv9kH2IjZm98HgKhfzww=)
    team: ENC(87x68MTJbd5UOO+d5VOj3A3x2+daClK1)
    key: ENC(cTYWSVUzAM4J3hTLvKT/kKJ1uh0kKMQ7)

  #Oauth2 login info
  security:
    oauth2:
      client:
        provider:
          apple:
            authorizationUri: https://appleid.apple.com/auth/authorize?scope=name%20email&response_mode=form_post
            tokenUri: https://appleid.apple.com/auth/token
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          apple:
            clientId: tripeer.tripeer.com
            clientSecret: ENC(qXlzbfeM3yV4/q5DTvsS6fi8js4NghcdYbty0WjoC/0=)
            redirect-uri: https://tripeer.co.kr/api/login/oauth2/code/apple
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Apple
            scope:
              - name
              - email
          kakao:
            client-name: kakao
            client-id: ENC(IaY6SQ0O/qVmqqwYfxphw2mNp3r82EjyJv62hGoqZfuFTM8rR7LUSqFWbxYS6x48)
            client-secret: ENC(lQlOiocOvFAtDivr/RySShuAQozGv1F6o1J6tf7uYxTeXxpl9BRgPUbvbDq69cix)
            redirect-uri: https://tripeer.co.kr/api/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-authentication-method: client_secret_post
          naver:
            client-name: naver
            client-id: ENC(6aRNPfKQdE/V+vszoh/xjRRmQiu8BHABuzs/t7DfYhQ=)
            client-secret: ENC(bjVify3O4qIWMbRrfzIpbj0P7Zm2uMpw)
            redirect-uri: https://tripeer.co.kr/api/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
          google:
            client-name: google
            client-id: ENC(sSX1umy4qajs8dX/VNp+Bvujw2PRjPcloD+s9GqSyUn8zRPfAh47doTxN2XPMO0Il+Nr48H280Ysd5Q/9hYpoSH+0ZzLJxXKeBWWNk+WiNlINJyc5SHHmQ==)
            client-secret: ENC(DTVN2JEtEbU8nBY0TJqMhfgkJG1cF+Gs/GNSIZ8Yd9j0q8PLkJnpEBP7FOGsS4cw)
            redirect-uri: https://tripeer.co.kr/api/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email

    #JWT Time 300min, 600min
  jwt:
    access: 600000
    refresh: 36000000
    secret: ENC(+TMgIEAtgPTpRvh8SSGMLDPoaEzVbkBA8RFQBsNplM5IAmNxrATCqM9itNRpS5BX)


  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(uLqb3uehjijt61z7bAolNDjE09x45e3laC0Vk26yIxA=)
    password: ENC(zhltywasMCbEhvwOVrmZJOXzsrK5B4weLd1RlrmRqQI=)
    debug: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true

odsay:
  apikey: ENC(WY4s6rkLclxdcAy0yC5Qzkz5srAwLMT1XChs29iWl59GKBggZbQW4isM/Lx75BVXfvIVkk4poNc=)

tmap:
  apikey: ENC(rq3bzD3hCoL+f1r9F3T1wYmAo6G7Y8UVawUT/x/0oYjUGj8gv8dgBByIo5YNDKOmKxYXlYqdBv8=)

kakao:
  #YHM
  apikey: ENC(P5ANnJgP83n706xcwZbbxZT5bg5Eypnt5peqQURgUOZoJ1llLhpq/8iJeS4iUF4l)
  #SDC
  apikey2: ENC(LmbA3fzJrrZsxzL3ulNlICYW+SZdR7H84p0yrbylVFm/5YcdoNnEBmZB8ml4QVN/)

weather:
  apikey: ENC(WgklgFHTOh8rQeyL+c475i5o48InrjPLAlkzE9rF30ZFK6+PSLxdYXIP68VbrGhpx01C8U7fxb8IRIjy1c03YobUpMxjOAyu2uTY6/xx20VtfNFYsyFsTzayeX8hOY+hmUObe/NMNEUDkXw0RAM+Hw==)

cloud:
  aws:
    credentials:
      accessKey: ENC(MDEIv0Elsed+UziTOhX2wkJGzw5jldwD0qxnjRVePpA=)
      secretKey: ENC(UZXZhURI7oZXplXNSYhkH0hUN0+rMIG4DkqDXvp2kufY5tY3UCv+hj3IRrvEnHrOxACeK2+jIRI=)
    s3:
      bucketName: tripeer207
    region:
      static: ap-northeast-2
  cloudformation:
    auto: false

  application:
    name: tripeer

admin:
  login: ENC(3At+j0WU3QGuxpq9ZOruxzROL2cCHGCd)


firebase:
  type: service_account
  project:
    id: tripeer-99eb2
  private:
    id: 4fc372d04a4290dc9b80c940d3d0c16ab516caea
    key:  "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCwpneMQ7XagEz5\nxRfR6MY822VKXTRZ5C0y8oj2ujIA6pKWfLJIr4HWF/WsAPwl/00F4Im+3SVzGtPf\nuR5XAQtM2Ouys8en/7XSJB3qFQC1qIaWdu6hbFRIqDGN/7QBgfbz4RXL7i+KcXcS\nCIdqAW0T7FlxP6j/KAfpLuWThl+ysrzh/0UDNxuA9TXuGf+8W8LZpCoVZCHkWzaR\nGLOeRJDGa6imqOFI2UiWjYGMdv9fl7aCd8pZzlIuHMXlBntwSNnUU2aO1rD0h4La\nt6pOwuLkySVka343D49x1Yxj4KE7x2h6lllp5X3bNqrfU3gaoicGHEiFuwGb4Mjs\ntPdPfVi5AgMBAAECggEACAMc4/9ENctg8mk2md45c5Qt5XARykv3otpuTOaIExOQ\nn4O7YGGZfXjruyf2R9DrEOusw7vrEWvzlS+jySVyekNSeXH/Cccm24eo1a+rLxIc\nPKHbU/YCYqNCUCL7aqAW79vTLcM5Y8mesXIyliPHa0JqkiDljOEnbrOiVQ0gtQ2j\n8tyruNC5Md8VChbsHAkC0OMqzHC7B4Ku4N+rmilEAqdg/rXoIJMKDMx34m9CJU+l\nLcDt7vBJwRj/j13FWJnfZ2DqbbGISiaiWyotegO7wz9mWyGqf2mKU8VI6vjxoymy\ntKuS/T+aAQ/dtfsVo0yQY8OJLw0EUod9wg1/qsQSgQKBgQDqUI69JybtteE0QEU8\nr9HgF1y2MqFXO2jc4KwaiRLV91le5MpufP+gzxAWVZeuLzrwLVHrVB7FbdcKQhnK\nqczjs8W2ubrQb8D/G6F3MOLly4VTJ81HrrVh87Y+jJYcJ/fBlWO6q9zNE+RoXasr\n3b0ya52K1d8U5nYNSznx3lBm4QKBgQDA/7WjE1vWPcUVK8n6uyRnI21UqDHkhOLQ\nk6euJ4G5F+XWACTpLHc00bypBAwuIYYzX24nuKE8n6c12zhqz8RC10dMTuPQAqaE\n+C7nnQ9rH0ePA+d+DQVpiVoGCRT8LQ8txmJ9ma6ro+SaG0ZotiNKyL/as+7A3kFT\ngSmSvy6k2QKBgGG7Hf4pQWRuszL/B6HrV6eXNvVLot3mirNuBnq+55tVIvKgjQqO\nmnSxSO13398oFfYtgPidyoPgb4v4zBcqwanLxtCTISdlJWOCW9OCEXF1dPOdK1MV\nvNPROhdWvhmaVg1pSQKIQn1LKb6aKxYN06cfGcPZtsVZ5q1ezhli97ghAoGAGZyV\nhRuXj1nJIqMZ/a0CCrHX22kqndHIq7c8hE731xFFzd1dCJh/BUJkD+Xam/CU95JN\ncvX8Z6gkL3B1Dy+dMuWQr560erEvWev5hYEBP8z52Q/Ck6a0timlCbIA1+o+3ms6\nPMK9PEfWmWDPOiwZiN4VH7fLEkssTiGQ28mFLhkCgYEAvHOj6YoyipIBosVwwEtm\n48vnLWmihsgYNjAADqyFuSRbqYhGR0yUrgz7aRdVB3vuh2n/H84ltLLk98oailLb\nCYOrvtx3g4yMRgs5lAz1o1BdArVJtmPgNHMVp5VbWzT7MBcbjSfG1lcCerIo8Gyk\nmi2agXGYbgUWauHIjKQaa+k=\n-----END PRIVATE KEY-----\n"
  client:
    id: 117689588121730634646
    email: firebase-adminsdk-ql7lm@tripeer-99eb2.iam.gserviceaccount.com
    x509:
      cert:
        url: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-ql7lm%40tripeer-99eb2.iam.gserviceaccount.com
  auth:
    uri: https://accounts.google.com/o/oauth2/auth
    provider:
      x509:
        cert:
          url: https://www.googleapis.com/oauth2/v1/certs
  token:
    uri: https://oauth2.googleapis.com/token
  universe:
    domain: googleapis.com



